//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramDebugConsole.BLL_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserB", Namespace="http://schemas.datacontract.org/2004/07/Discussme.BLL.DbObjects")]
    [System.SerializableAttribute()]
    public partial class UserB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastSeenTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPrivacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBanned {
            get {
                return this.IsBannedField;
            }
            set {
                if ((this.IsBannedField.Equals(value) != true)) {
                    this.IsBannedField = value;
                    this.RaisePropertyChanged("IsBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastSeenTime {
            get {
                return this.LastSeenTimeField;
            }
            set {
                if ((this.LastSeenTimeField.Equals(value) != true)) {
                    this.LastSeenTimeField = value;
                    this.RaisePropertyChanged("LastSeenTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationTime {
            get {
                return this.RegistrationTimeField;
            }
            set {
                if ((this.RegistrationTimeField.Equals(value) != true)) {
                    this.RegistrationTimeField = value;
                    this.RaisePropertyChanged("RegistrationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPrivacy {
            get {
                return this.UserPrivacyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPrivacyField, value) != true)) {
                    this.UserPrivacyField = value;
                    this.RaisePropertyChanged("UserPrivacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRoleField, value) != true)) {
                    this.UserRoleField = value;
                    this.RaisePropertyChanged("UserRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/Discussme.BLL.DbObjects")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SectionB", Namespace="http://schemas.datacontract.org/2004/07/Discussme.BLL.DbObjects")]
    [System.SerializableAttribute()]
    public partial class SectionB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopicB", Namespace="http://schemas.datacontract.org/2004/07/Discussme.BLL.DbObjects")]
    [System.SerializableAttribute()]
    public partial class TopicB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SectionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SectionId {
            get {
                return this.SectionIdField;
            }
            set {
                if ((this.SectionIdField.Equals(value) != true)) {
                    this.SectionIdField = value;
                    this.RaisePropertyChanged("SectionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommentB", Namespace="http://schemas.datacontract.org/2004/07/Discussme.BLL.DbObjects")]
    [System.SerializableAttribute()]
    public partial class CommentB : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TopicIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TopicId {
            get {
                return this.TopicIdField;
            }
            set {
                if ((this.TopicIdField.Equals(value) != true)) {
                    this.TopicIdField = value;
                    this.RaisePropertyChanged("TopicId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL_Service.IForumService")]
    public interface IForumService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RegisterUser", ReplyAction="http://tempuri.org/IForumService/RegisterUserResponse")]
        bool RegisterUser([System.ServiceModel.MessageParameterAttribute(Name="registerUser")] ProgramDebugConsole.BLL_Service.UserB registerUser1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RegisterUser", ReplyAction="http://tempuri.org/IForumService/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(ProgramDebugConsole.BLL_Service.UserB registerUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/Login", ReplyAction="http://tempuri.org/IForumService/LoginResponse")]
        bool Login(ProgramDebugConsole.BLL_Service.LoginData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/Login", ReplyAction="http://tempuri.org/IForumService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(ProgramDebugConsole.BLL_Service.LoginData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/ChangeData", ReplyAction="http://tempuri.org/IForumService/ChangeDataResponse")]
        bool ChangeData(ProgramDebugConsole.BLL_Service.UserB toChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/ChangeData", ReplyAction="http://tempuri.org/IForumService/ChangeDataResponse")]
        System.Threading.Tasks.Task<bool> ChangeDataAsync(ProgramDebugConsole.BLL_Service.UserB toChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddSection", ReplyAction="http://tempuri.org/IForumService/AddSectionResponse")]
        void AddSection(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddSection", ReplyAction="http://tempuri.org/IForumService/AddSectionResponse")]
        System.Threading.Tasks.Task AddSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddTopic", ReplyAction="http://tempuri.org/IForumService/AddTopicResponse")]
        void AddTopic(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddTopic", ReplyAction="http://tempuri.org/IForumService/AddTopicResponse")]
        System.Threading.Tasks.Task AddTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddComment", ReplyAction="http://tempuri.org/IForumService/AddCommentResponse")]
        void AddComment(ProgramDebugConsole.BLL_Service.CommentB comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/AddComment", ReplyAction="http://tempuri.org/IForumService/AddCommentResponse")]
        System.Threading.Tasks.Task AddCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllSections", ReplyAction="http://tempuri.org/IForumService/GetAllSectionsResponse")]
        ProgramDebugConsole.BLL_Service.SectionB[] GetAllSections();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllSections", ReplyAction="http://tempuri.org/IForumService/GetAllSectionsResponse")]
        System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.SectionB[]> GetAllSectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetTopicsInSection", ReplyAction="http://tempuri.org/IForumService/GetTopicsInSectionResponse")]
        ProgramDebugConsole.BLL_Service.TopicB[] GetTopicsInSection(int sectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetTopicsInSection", ReplyAction="http://tempuri.org/IForumService/GetTopicsInSectionResponse")]
        System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.TopicB[]> GetTopicsInSectionAsync(int sectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetCommentsInTopic", ReplyAction="http://tempuri.org/IForumService/GetCommentsInTopicResponse")]
        ProgramDebugConsole.BLL_Service.CommentB[] GetCommentsInTopic(int topicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetCommentsInTopic", ReplyAction="http://tempuri.org/IForumService/GetCommentsInTopicResponse")]
        System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.CommentB[]> GetCommentsInTopicAsync(int topicId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllTopicsByPredicate", ReplyAction="http://tempuri.org/IForumService/GetAllTopicsByPredicateResponse")]
        ProgramDebugConsole.BLL_Service.TopicB[] GetAllTopicsByPredicate(System.Func<ProgramDebugConsole.BLL_Service.TopicB, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllTopicsByPredicate", ReplyAction="http://tempuri.org/IForumService/GetAllTopicsByPredicateResponse")]
        System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.TopicB[]> GetAllTopicsByPredicateAsync(System.Func<ProgramDebugConsole.BLL_Service.TopicB, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllComentsByPredicate", ReplyAction="http://tempuri.org/IForumService/GetAllComentsByPredicateResponse")]
        ProgramDebugConsole.BLL_Service.CommentB[] GetAllComentsByPredicate(System.Func<ProgramDebugConsole.BLL_Service.CommentB, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/GetAllComentsByPredicate", ReplyAction="http://tempuri.org/IForumService/GetAllComentsByPredicateResponse")]
        System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.CommentB[]> GetAllComentsByPredicateAsync(System.Func<ProgramDebugConsole.BLL_Service.CommentB, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateSection", ReplyAction="http://tempuri.org/IForumService/UpdateSectionResponse")]
        void UpdateSection(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateSection", ReplyAction="http://tempuri.org/IForumService/UpdateSectionResponse")]
        System.Threading.Tasks.Task UpdateSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateComment", ReplyAction="http://tempuri.org/IForumService/UpdateCommentResponse")]
        void UpdateComment(ProgramDebugConsole.BLL_Service.CommentB comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateComment", ReplyAction="http://tempuri.org/IForumService/UpdateCommentResponse")]
        System.Threading.Tasks.Task UpdateCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateTopic", ReplyAction="http://tempuri.org/IForumService/UpdateTopicResponse")]
        void UpdateTopic(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/UpdateTopic", ReplyAction="http://tempuri.org/IForumService/UpdateTopicResponse")]
        System.Threading.Tasks.Task UpdateTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveSection", ReplyAction="http://tempuri.org/IForumService/RemoveSectionResponse")]
        void RemoveSection(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveSection", ReplyAction="http://tempuri.org/IForumService/RemoveSectionResponse")]
        System.Threading.Tasks.Task RemoveSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveTopic", ReplyAction="http://tempuri.org/IForumService/RemoveTopicResponse")]
        void RemoveTopic(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveTopic", ReplyAction="http://tempuri.org/IForumService/RemoveTopicResponse")]
        System.Threading.Tasks.Task RemoveTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveComment", ReplyAction="http://tempuri.org/IForumService/RemoveCommentResponse")]
        void RemoveComment(ProgramDebugConsole.BLL_Service.CommentB comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumService/RemoveComment", ReplyAction="http://tempuri.org/IForumService/RemoveCommentResponse")]
        System.Threading.Tasks.Task RemoveCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumServiceChannel : ProgramDebugConsole.BLL_Service.IForumService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForumServiceClient : System.ServiceModel.ClientBase<ProgramDebugConsole.BLL_Service.IForumService>, ProgramDebugConsole.BLL_Service.IForumService {
        
        public ForumServiceClient() {
        }
        
        public ForumServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForumServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(ProgramDebugConsole.BLL_Service.UserB registerUser1) {
            return base.Channel.RegisterUser(registerUser1);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(ProgramDebugConsole.BLL_Service.UserB registerUser) {
            return base.Channel.RegisterUserAsync(registerUser);
        }
        
        public bool Login(ProgramDebugConsole.BLL_Service.LoginData data) {
            return base.Channel.Login(data);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(ProgramDebugConsole.BLL_Service.LoginData data) {
            return base.Channel.LoginAsync(data);
        }
        
        public bool ChangeData(ProgramDebugConsole.BLL_Service.UserB toChange) {
            return base.Channel.ChangeData(toChange);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeDataAsync(ProgramDebugConsole.BLL_Service.UserB toChange) {
            return base.Channel.ChangeDataAsync(toChange);
        }
        
        public void AddSection(ProgramDebugConsole.BLL_Service.SectionB section) {
            base.Channel.AddSection(section);
        }
        
        public System.Threading.Tasks.Task AddSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section) {
            return base.Channel.AddSectionAsync(section);
        }
        
        public void AddTopic(ProgramDebugConsole.BLL_Service.TopicB topic) {
            base.Channel.AddTopic(topic);
        }
        
        public System.Threading.Tasks.Task AddTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic) {
            return base.Channel.AddTopicAsync(topic);
        }
        
        public void AddComment(ProgramDebugConsole.BLL_Service.CommentB comment) {
            base.Channel.AddComment(comment);
        }
        
        public System.Threading.Tasks.Task AddCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment) {
            return base.Channel.AddCommentAsync(comment);
        }
        
        public ProgramDebugConsole.BLL_Service.SectionB[] GetAllSections() {
            return base.Channel.GetAllSections();
        }
        
        public System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.SectionB[]> GetAllSectionsAsync() {
            return base.Channel.GetAllSectionsAsync();
        }
        
        public ProgramDebugConsole.BLL_Service.TopicB[] GetTopicsInSection(int sectionId) {
            return base.Channel.GetTopicsInSection(sectionId);
        }
        
        public System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.TopicB[]> GetTopicsInSectionAsync(int sectionId) {
            return base.Channel.GetTopicsInSectionAsync(sectionId);
        }
        
        public ProgramDebugConsole.BLL_Service.CommentB[] GetCommentsInTopic(int topicId) {
            return base.Channel.GetCommentsInTopic(topicId);
        }
        
        public System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.CommentB[]> GetCommentsInTopicAsync(int topicId) {
            return base.Channel.GetCommentsInTopicAsync(topicId);
        }
        
        public ProgramDebugConsole.BLL_Service.TopicB[] GetAllTopicsByPredicate(System.Func<ProgramDebugConsole.BLL_Service.TopicB, bool> predicate) {
            return base.Channel.GetAllTopicsByPredicate(predicate);
        }
        
        public System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.TopicB[]> GetAllTopicsByPredicateAsync(System.Func<ProgramDebugConsole.BLL_Service.TopicB, bool> predicate) {
            return base.Channel.GetAllTopicsByPredicateAsync(predicate);
        }
        
        public ProgramDebugConsole.BLL_Service.CommentB[] GetAllComentsByPredicate(System.Func<ProgramDebugConsole.BLL_Service.CommentB, bool> predicate) {
            return base.Channel.GetAllComentsByPredicate(predicate);
        }
        
        public System.Threading.Tasks.Task<ProgramDebugConsole.BLL_Service.CommentB[]> GetAllComentsByPredicateAsync(System.Func<ProgramDebugConsole.BLL_Service.CommentB, bool> predicate) {
            return base.Channel.GetAllComentsByPredicateAsync(predicate);
        }
        
        public void UpdateSection(ProgramDebugConsole.BLL_Service.SectionB section) {
            base.Channel.UpdateSection(section);
        }
        
        public System.Threading.Tasks.Task UpdateSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section) {
            return base.Channel.UpdateSectionAsync(section);
        }
        
        public void UpdateComment(ProgramDebugConsole.BLL_Service.CommentB comment) {
            base.Channel.UpdateComment(comment);
        }
        
        public System.Threading.Tasks.Task UpdateCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment) {
            return base.Channel.UpdateCommentAsync(comment);
        }
        
        public void UpdateTopic(ProgramDebugConsole.BLL_Service.TopicB topic) {
            base.Channel.UpdateTopic(topic);
        }
        
        public System.Threading.Tasks.Task UpdateTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic) {
            return base.Channel.UpdateTopicAsync(topic);
        }
        
        public void RemoveSection(ProgramDebugConsole.BLL_Service.SectionB section) {
            base.Channel.RemoveSection(section);
        }
        
        public System.Threading.Tasks.Task RemoveSectionAsync(ProgramDebugConsole.BLL_Service.SectionB section) {
            return base.Channel.RemoveSectionAsync(section);
        }
        
        public void RemoveTopic(ProgramDebugConsole.BLL_Service.TopicB topic) {
            base.Channel.RemoveTopic(topic);
        }
        
        public System.Threading.Tasks.Task RemoveTopicAsync(ProgramDebugConsole.BLL_Service.TopicB topic) {
            return base.Channel.RemoveTopicAsync(topic);
        }
        
        public void RemoveComment(ProgramDebugConsole.BLL_Service.CommentB comment) {
            base.Channel.RemoveComment(comment);
        }
        
        public System.Threading.Tasks.Task RemoveCommentAsync(ProgramDebugConsole.BLL_Service.CommentB comment) {
            return base.Channel.RemoveCommentAsync(comment);
        }
    }
}
