//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramDebugConsole.BLL_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLL_Service.IForumDataService")]
    public interface IForumDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumDataService/AddSection", ReplyAction="http://tempuri.org/IForumDataService/AddSectionResponse")]
        void AddSection(int id, string title, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForumDataService/AddSection", ReplyAction="http://tempuri.org/IForumDataService/AddSectionResponse")]
        System.Threading.Tasks.Task AddSectionAsync(int id, string title, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForumDataServiceChannel : ProgramDebugConsole.BLL_Service.IForumDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForumDataServiceClient : System.ServiceModel.ClientBase<ProgramDebugConsole.BLL_Service.IForumDataService>, ProgramDebugConsole.BLL_Service.IForumDataService {
        
        public ForumDataServiceClient() {
        }
        
        public ForumDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForumDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForumDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSection(int id, string title, string description) {
            base.Channel.AddSection(id, title, description);
        }
        
        public System.Threading.Tasks.Task AddSectionAsync(int id, string title, string description) {
            return base.Channel.AddSectionAsync(id, title, description);
        }
    }
}
